### ISSUE TITLE
skimage.io.imread sometimes reads images/labels as 'RGB'

### ISSUE THREAD

**Issue by Mohinta2892** [danifranco/EM_domain_adaptation#1]
Hi Daniel,

In Att_YNet_notebook `get_xy_image_list(dir)` the following line sometimes reads the images as 'RGB' with shapes `H x W x 3`, which subsequently raises an error at the generator instantiation stage.

```train_img = [ img_as_ubyte( np.array(io.imread( x ), dtype='uint8')) for x in train_input_filenames ]```

 `as_gray=True` must be passed such as below to make it explicit:

```train_img = [ img_as_ubyte( np.array(io.imread( x, as_gray=True ), dtype='uint8')) for x in train_input_filenames ]```

I am using scikit-image == 0.21.0

If you could please make this addition that would be great. Also, happy to submit a pull request.

Best,
Samia

**Comment by danifranco** [comment]
Hello,

Thank you so much for pointing out the error. I have just commited some changes to ensure that whenever we use io.imread a grayscale image is read. 

Please, feel free to close the issue if you do not find any additional problem.

Best,

Dani

**Comment by Mohinta2892** [comment]
Many thanks Dani. Closing for now!
